name: Build image
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Convert OWNER to lowercase
        run: echo "OWNER_LOWERCASE=$(echo ${{ env.OWNER }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ env.OWNER }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LOWERCASE }}/${{ env.REPOSITORY }}:latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7
      - name: Delete older packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.REPOSITORY }}
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
